services:
  - type: web
    name: aura-crm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
